## **Importing Libraries**

In [ ]:
import torch
import numpy as np

# **Basics of Tensors**

Creating tensor from numpy array using 'from_numpy' or 'as_tensor' method

In [ ]:
arr = np.array([5,8,2,10,574,8])
type(arr)

numpy.ndarray

In [ ]:
# Creating tensor from numpy array using 'from_numpy' or 'as_tensor' method
t1 = torch.from_numpy(arr)
t1

tensor([  5,   8,   2,  10, 574,   8])

In [ ]:
len(t1)

6

In [ ]:
torch.as_tensor(arr)

tensor([  5,   8,   2,  10, 574,   8])

'from_numpy' & 'as_tensor' methods share the same memory of the numpy array from which tensor has been created.So if any change is being done to the numpy array, it would reflect in the tensors too.

In [ ]:
# 'from_numpy' & 'as_tensor' methods share the same memory of the numpy array from which tensor has been created.
# So if any change is being done to the numpy array, it would reflect in the tensors too.
arr[2]=158
arr

array([  5,   8, 158,  10, 574,   8])

In [ ]:
t1

tensor([  5,   8, 158,  10, 574,   8])

In order to avoid this, and to make a permanent copy of tensor, 'tensor' method can be used.

In [ ]:
# In order to avoid this, and to make a permanent copy of tensor, 'tensor' method can be used.
t2 = torch.tensor(arr)
t2

tensor([  5,   8, 158,  10, 574,   8])

In [ ]:
arr[1] = 100
arr

array([  5, 100, 158,  10, 574,   8])

In [ ]:
t1, t2

(tensor([  5, 100, 158,  10, 574,   8]),
 tensor([  5,   8, 158,  10, 574,   8]))

'torch.Tensor' would result in float dtype, whereas 'torch.tensor' would retain the original dtype.

In [ ]:
# 'torch.Tensor' would result in float dtype, whereas 'torch.tensor' would retain the original dtype.
t3 = torch.Tensor(arr)
t2.dtype, t3.dtype

(torch.int64, torch.float32)

Creating zero tensors

In [ ]:
# creating zero tensors
torch.zeros(5,2, dtype=torch.int64)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

Creating unit tensors

In [ ]:
# creating unit tensors
torch.ones(3,2, dtype=torch.int32)

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

Creating arange value tensors

In [ ]:
# creating arange value tensors
torch.arange(0,20,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
torch.arange(0,20,2).reshape(5,2)

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]])

Creating linspace tensors

In [ ]:
# creating linspace tensors
my_tensor = torch.linspace(0,20,15).reshape(3,5)
my_tensor

tensor([[ 0.0000,  1.4286,  2.8571,  4.2857,  5.7143],
        [ 7.1429,  8.5714, 10.0000, 11.4286, 12.8571],
        [14.2857, 15.7143, 17.1429, 18.5714, 20.0000]])

In [ ]:
len(my_tensor)

3

Changing the data type of tensors

In [ ]:
# changing the data type of tensors
my_tensor.dtype

torch.float32

In [ ]:
changed_tensor = my_tensor.type(torch.int32)
changed_tensor

tensor([[ 0,  1,  2,  4,  5],
        [ 7,  8, 10, 11, 12],
        [14, 15, 17, 18, 20]], dtype=torch.int32)

Creating random tensor with uniform distribution of 0,1

In [ ]:
# creating random tensor with uniform distribution of 0,1
torch.rand(2,5)

tensor([[0.9293, 0.0119, 0.0819, 0.4405, 0.9886],
        [0.0388, 0.2862, 0.9650, 0.3732, 0.4460]])

Creating random tensor with a normal distribution (mean=0, std_dev=1)

In [ ]:
# creating random tensor with a normal distribution (mean=0, std_dev=1)
torch.randn(3,3)

tensor([[-0.6926, -1.1617,  1.5422],
        [ 1.0705,  0.1184, -1.0134],
        [ 1.4150,  0.4125, -0.3817]])

Creating random tensors with any upper & lower limits

In [ ]:
# creating random tensors with any upper & lower limits
torch.randint(low=0,high=15,size=(5,5)) # here, high value is excluded and low value is included

tensor([[ 2,  9, 12,  6,  0],
        [11,  7,  0, 14, 13],
        [ 4, 13, 13,  0,  5],
        [ 9, 12,  0,  7, 11],
        [ 7,  6,  8,  2,  7]])

Creating a random tensor like the shape of another tensor

In [ ]:
# creating a random tensor like the shape of another tensor
a1 = torch.zeros(5,2)
a1

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
torch.randn_like(a1) #takes the shape of a1. Other available options are 'rand_like' etc.

tensor([[ 1.6389,  0.2560],
        [ 0.1239, -1.2916],
        [ 1.4073, -1.4173],
        [ 1.0776,  0.3770],
        [ 0.2266, -0.0541]])

Setting the seed value of generating random tensors

In [ ]:
# setting the seed value of generating random tensors
torch.manual_seed(32)

## **Tensor Operations**

In [ ]:
x1 = torch.arange(10).reshape(2,5)
x1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Indexing of tensors

In [ ]:
x1[0,3] #returns as tensor

tensor(3)

In [ ]:
x1[:,2] # returns the 3rd column

tensor([2, 7])

Performing arithmetic operations on tensors

In [ ]:
t1, t2

(tensor([  5, 100, 158,  10, 574,   8]),
 tensor([  5,   8, 158,  10, 574,   8]))

In [ ]:
# performing arithmetic operations on tensors
t2+2, t2*2, t2-10, t2/2

(tensor([  7,  10, 160,  12, 576,  10]),
 tensor([  10,   16,  316,   20, 1148,   16]),
 tensor([ -5,  -2, 148,   0, 564,  -2]),
 tensor([  2.5000,   4.0000,  79.0000,   5.0000, 287.0000,   4.0000]))

Adding two Tensors

In [ ]:
#adding two tensors
t1+t2

tensor([  10,  108,  316,   20, 1148,   16])

Performing Dot products on two tensors

In [ ]:
t1.dot(t2)

tensor(355429)

Performing Matrix Multiplication on two tensors

In [ ]:
x = torch.arange(10).reshape(2,5)
y = torch.arange(10).reshape(5,2)
print(x)
print(y)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [ ]:
torch.mm(x,y)

tensor([[ 60,  70],
        [160, 195]])

'@' can be used to perform Matrix Multiplication

In [ ]:
x @ y

tensor([[ 60,  70],
        [160, 195]])

## **Backpropagation**

In [ ]:
a1 = torch.tensor(2., requires_grad=True) #float values should be given, if 'requires_grad' is True

Consider the sample equation

$g = 3a_1^4 + 2a_1^3 + 5a_1^2 + 10a_1 + 25$ 

In [ ]:
g = 3*a1**4 + 2*a1**3 + 5*a1**2 + 10*a1 + 25

In [ ]:
print(g)

tensor(129., grad_fn=<AddBackward0>)


Differentiating the function $g$

In [ ]:
g.backward()

Now, $g' = 12a_1^3 + 6a_1^2 + 10a_1 + 10$

Getting the slope at $a_1 = 2$

In [ ]:
a1.grad

tensor(150.)

Performing backpropagation on matrices

In [ ]:
m1 = torch.tensor([[2.,5.,8.],[10.,25.,11.]], requires_grad=True)

In [ ]:
g2 = 3*m1 + 20

In [ ]:
print(g2)

tensor([[26., 35., 44.],
        [50., 95., 53.]], grad_fn=<AddBackward0>)


In [ ]:
out = g2.mean()
print(out)

tensor(50.5000, grad_fn=<MeanBackward0>)


In [ ]:
out.backward()

In [ ]:
m1.grad

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])